(function(){
  const SUPABASE_URL='https://opsactnkcyskznktfdbi.supabase.co';
  const SUPABASE_KEY='sb_publishable_VFeoxXQW18SpPdH2MBP3dw_tbUhj0Vm';
  const SESSION_KEY='ielts-supabase-session-v1'; const listeners=[]; let session=null;
  try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){}
  function saveSession(s){session=s||null;if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY);listeners.forEach(fn=>{try{fn(session?'SIGNED_IN':'SIGNED_OUT',session)}catch(e){}})}
  async function req(path,opts={}){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json',...(opts.headers||{})};if(opts.auth!==false&&session?.access_token)headers.Authorization='Bearer '+session.access_token;const r=await fetch(SUPABASE_URL+path,{...opts,headers});let data=null;try{data=await r.json()}catch(e){}if(!r.ok){const err=new Error(data?.msg||data?.message||data?.error_description||data?.error||('HTTP '+r.status));err.status=r.status;throw err}return data}
  async function refreshIfNeeded(){if(!session)return null;if((session.expires_at||0)*1000>Date.now()+60000)return session;if(!session.refresh_token){saveSession(null);return null}try{const d=await req('/auth/v1/token?grant_type=refresh_token',{method:'POST',auth:false,body:JSON.stringify({refresh_token:session.refresh_token})});saveSession({...d,user:d.user,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)});return session}catch(e){saveSession(null);return null}}
  function makeQuery(table){let filters=[];const q={select(cols='*'){q._cols=cols;return q},eq(col,val){filters.push([col,val]);return q},async maybeSingle(){await refreshIfNeeded();let url='/rest/v1/'+encodeURIComponent(table)+'?select='+encodeURIComponent(q._cols||'*');filters.forEach(([c,v])=>url+='&'+encodeURIComponent(c)+'=eq.'+encodeURIComponent(v));try{return {data:await req(url,{method:'GET',headers:{Accept:'application/vnd.pgrst.object+json'}}),error:null}}catch(e){if(e.status===406)return {data:null,error:null};return {data:null,error:e}}},async upsert(obj,options={}){await refreshIfNeeded();try{return {data:await req('/rest/v1/'+encodeURIComponent(table)+(options.onConflict?'?on_conflict='+encodeURIComponent(options.onConflict):''),{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(obj)}),error:null}}catch(e){return {data:null,error:e}}}};return q}
  const client={auth:{async signInWithPassword(creds){try{const d=await req('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:JSON.stringify(creds)}),s={...d,user:d.user,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)};saveSession(s);return {data:{user:d.user,session:s},error:null}}catch(e){return {data:{user:null,session:null},error:e}}},async signUp(creds){try{const d=await req('/auth/v1/signup',{method:'POST',auth:false,body:JSON.stringify(creds)}),s=d.access_token?{...d,user:d.user,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600)}:null;if(s)saveSession(s);return {data:{user:d.user,session:s},error:null}}catch(e){return {data:{user:null,session:null},error:e}}},async signOut(){try{if(session?.access_token)await req('/auth/v1/logout',{method:'POST'})}catch(e){}saveSession(null);return {error:null}},async getSession(){await refreshIfNeeded();return {data:{session},error:null}},onAuthStateChange(fn){listeners.push(fn);return {data:{subscription:{unsubscribe(){const i=listeners.indexOf(fn);if(i>=0)listeners.splice(i,1)}}}}}},from:makeQuery};
  window.supabase=window.supabase||{createClient(){return client}};
  let user=null,timer=null,cloudCache={};
  const norm=s=>(s||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').trim(); const canonical=q=>'q::'+norm(q);
  function idx(){const byNorm=new Map(),byKey=new Map();(window.IELTS_DATA||[]).forEach(r=>r.questions.forEach((q,i)=>{const x={r,i,key:r.id+'::'+i,q};byNorm.set(norm(q),x);byKey.set(x.key,x)}));return {byNorm,byKey}}
  function customItems(cloud){const out=new Map(),add=cloud?.__custom__?.addTo||{};Object.values(add).flat().forEach(x=>{if(x?.id&&x?.question)out.set(norm(x.question),x)});return out}
  function obj(v){if(!v)return null;if(typeof v==='string')return {answer:v,updatedAt:new Date(0).toISOString()};return typeof v==='object'?v:null}
  function merge(a,b){a=obj(a)||{};b=obj(b)||{};const ta=Date.parse(a.updatedAt||0)||0,tb=Date.parse(b.updatedAt||0)||0;const newer=tb>ta?b:a,older=tb>ta?a:b;return {...older,...newer}}
  async function getCloud(){if(!user)return {};const {data,error}=await client.from('user_answers').select('answers').eq('user_id',user.id).maybeSingle();if(error)throw error;return data?.answers&&typeof data.answers==='object'?data.answers:{}}
  async function putCloud(c){if(!user)return;const {error}=await client.from('user_answers').upsert({user_id:user.id,answers:c,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;cloudCache=c}
  function exposeMeta(key,v){window.IELTS_CLOUD_META=window.IELTS_CLOUD_META||{};window.IELTS_CLOUD_META[key]=v}
  async function migrate(){if(!user||typeof saved==='undefined')return;const cloud=await getCloud(),I=idx(),custom=customItems(cloud);cloudCache=cloud;let changed=false;
    I.byNorm.forEach((cur,nq)=>{const ci=custom.get(nq),ck=canonical(cur.q);let best=merge(cloud[ck],cloud[cur.key]);if(ci)best=merge(best,cloud[ci.id]);if(Object.keys(best).length){cloud[ck]=best;cloud[cur.key]=best;if(ci)cloud[ci.id]=best;exposeMeta(cur.key,{...best,question:cur.q,hint:ci?.hint||'',part:ci?.part||cur.r.part})}if(typeof best.answer==='string'&&saved[cur.key]!==best.answer){saved[cur.key]=best.answer;changed=true}});
    // Dynamic matching means new custom questions and future suggestions require no hard-coded category mapping.
    window.IELTS_P23_LINKS=cloud?.__custom__?.p23links||{}; window.IELTS_CUSTOM=cloud?.__custom__||{};
    localStorage.setItem(KEY,JSON.stringify(saved));await putCloud(cloud);if(changed){renderHome?.();updateStats?.();if(typeof practice!=='undefined'&&practice.style.display!=='none')renderPractice?.()}
    window.dispatchEvent(new CustomEvent('ielts-cloud-ready',{detail:{meta:window.IELTS_CLOUD_META||{},links:window.IELTS_P23_LINKS}}));
  }
  async function syncCurrent(){if(!user||typeof DATA==='undefined'||typeof saved==='undefined'||activeTopic==null)return;const r=DATA[activeTopic],q=r?.questions?.[qIndex];if(!q)return;const key=r.id+'::'+qIndex,val=saved[key];if(val===undefined)return;const cloud=await getCloud(),custom=customItems(cloud),ci=custom.get(norm(q));let rec=merge(cloud[key],cloud[canonical(q)]);if(ci)rec=merge(rec,cloud[ci.id]);rec={...rec,answer:val,updatedAt:new Date().toISOString()};cloud[key]=rec;cloud[canonical(q)]=rec;if(ci)cloud[ci.id]=rec;await putCloud(cloud);exposeMeta(key,{...rec,question:q,hint:ci?.hint||'',part:ci?.part||r.part});window.dispatchEvent(new CustomEvent('ielts-cloud-saved',{detail:{key}}))}
  function schedule(){clearTimeout(timer);timer=setTimeout(syncCurrent,550)}
  window.IELTS_SYNC={getMeta:key=>(window.IELTS_CLOUD_META||{})[key]||null,getLinks:()=>window.IELTS_P23_LINKS||{},refresh:migrate,save:schedule};
  window.addEventListener('load',async()=>{try{const {data}=await client.auth.getSession();user=data.session?.user||null;if(user)await migrate();client.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user)setTimeout(migrate,120)});const a=window.answerInput;if(typeof a==='function')window.answerInput=function(){a();schedule()};const p=window.persist;if(typeof p==='function')window.persist=function(){p();schedule()}}catch(e){console.warn('Supabase sync unavailable',e)}});
})();